name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: LaTeX compilation
      uses: xu-cheng/latex-action@master
      with:
        working_directory: AL1
        root_file: main.tex
    - name: LaTeX compilation
      uses: xu-cheng/latex-action@master
      with:
        working_directory: MD
        root_file: main.tex
    - name: Prepare PDFS
      run: |
        ls -R
        mkdir build && cp -r AL1/ MD/ build/ && find build/ -type f ! -name '*.pdf' -delete
    - name: Push PDFS to repo
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
