name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: LaTeX compilation
      uses: xu-cheng/latex-action@master
      with:
        root_file: "**/*.tex"
        glob_root_file: true
    - name: Prepare PDFS
      run: |
        mkdir build && cp *.pdf build/
    - name: Push PDFS to repo
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
